### ISSUE TITLE
롤링페이퍼 완료 페이지 작업

### ISSUE THREAD

**Issue by KIM-DONGJU** [sungkuk5420/rolling-papers#4]
https://www.figma.com/file/BE0oq353XwcyMDLH1wUjJp/%EB%A1%A4%EB%A7%81%ED%8E%98%EC%9D%B4%ED%8D%BC?node-id=414%3A2572&t=kIz3ny7OCHSXuBq4-4

부터 쭉 작업

**Comment by barogo-KIMDONGJU** [comment]
1차 완료는 했으나 디자인이 업데이트 되어서 업데이트 적용 필요
